In [1]:
import numpy as np

array_1 = np.array([1,2,3])
print(array_1)


[1 2 3]


In [2]:
array_2 = array_1 ** 2
print(array_2)


[1 4 9]


In [3]:
array_3 = array_1 + array_2
print(array_3)

[ 2  6 12]


In [4]:
list_1 = [i for i in range(1,6)]
print(list_1)

[1, 2, 3, 4, 5]


In [8]:
array_4 = np.array(list_1)

print(f'Sine: {np.sin(array_4)}')

Sine: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [9]:
print(f'Exponential: {np.exp(array_4)}')



Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
