In [6]:
import numpy as np
import random

print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [9]:
print(np.eye(2))



[[1. 0.]
 [0. 1.]]


In [10]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
print(np.random.randint(1, 20, (4,3)))


[[ 8 10  4]
 [ 2 12 15]
 [10 10 13]
 [ 4  7  1]]


In [12]:
a = np.random.randint(1, 100, 30)
print(a)

[23 23 64 70 60 17 90 13 88 24 32 17 60 85 22 46  5 99 59 69 25 71 96 68
  6 12 24 47  9 85]


In [13]:
b = a.reshape(2,3,5)
print(b)

[[[23 23 64 70 60]
  [17 90 13 88 24]
  [32 17 60 85 22]]

 [[46  5 99 59 69]
  [25 71 96 68  6]
  [12 24 47  9 85]]]


In [14]:
c = a.reshape(6,5)
print(c)

[[23 23 64 70 60]
 [17 90 13 88 24]
 [32 17 60 85 22]
 [46  5 99 59 69]
 [25 71 96 68  6]
 [12 24 47  9 85]]


In [16]:
print(a.shape)
print(b.shape)
print(c.shape)

(30,)
(2, 3, 5)
(6, 5)


In [18]:
a1 = np.arange(0,21,2)
print(a1)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [20]:
print(a1[[2,4,9]])

[ 4  8 18]


In [21]:
m1 = np.random.randint(10, 100, 15).reshape(3,5)
print(m1)


[[54 67 69 69 92]
 [41 26 65 89 26]
 [40 63 86 53 11]]


In [22]:
print(m1[2][3])


53


In [25]:
print(m1[1,4])

26


In [26]:
print(m1[:,3])

[69 89 53]


In [27]:
print(m1[0:2, 1])

[67 26]


In [28]:
print(m1[0:2, 2:4])


[[69 69]
 [65 89]]


In [30]:
print(m1[0:2, [1,3]])

[[67 69]
 [26 89]]


In [32]:
m2 = np.random.randint(10, 100, 15).reshape(3,5)
print(m2)

[[51 15 51 18 24]
 [96 18 66 22 12]
 [60 72 70 27 68]]


In [34]:
print(m2[m2>50])

AttributeError: 'numpy.ndarray' object has no attribute 'count'

In [35]:
print(len(m2[m2>50]))


8
