In [3]:
import numpy as np

m1 = np.random.randint(1, 10, 9).reshape(3,3)
m2 = np.random.randint(1, 10, 9).reshape(3,3)
print(m1)
print(m2)

[[1 2 2]
 [1 8 8]
 [6 3 4]]
[[5 1 7]
 [7 3 8]
 [3 1 7]]


In [4]:
m3 = m1 * m2
print(m3)

[[ 5  2 14]
 [ 7 24 64]
 [18  3 28]]


In [5]:
m4 = m3 ** 2
print(m4)

[[  25    4  196]
 [  49  576 4096]
 [ 324    9  784]]


In [6]:
m5 = m4 // m2
print(m5)

[[  5   4  28]
 [  7 192 512]
 [108   9 112]]


In [9]:
# stacking arrays
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(np.vstack((a,b)))
print('==============')
print(np.hstack((a,b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
